// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email, password, role
) VALUES (
    $1, $2, $3
) RETURNING id, email, password, role, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email    string   `json:"email"`
	Password string   `json:"password"`
	Role     RoleEnum `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Password, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMe = `-- name: GetMe :one
SELECT u.id, u.email, u.role, u.created_at, 
       o.name as occupant_name, o.phone_number as occupant_phone,
       op.name as operator_name, op.phone_number as operator_phone
FROM users u
LEFT JOIN occupant_details o ON u.id = o.user_id
LEFT JOIN operator_details op ON u.id = op.user_id
WHERE u.id = $1 LIMIT 1
`

type GetMeRow struct {
	ID            uuid.UUID          `json:"id"`
	Email         string             `json:"email"`
	Role          RoleEnum           `json:"role"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	OccupantName  pgtype.Text        `json:"occupant_name"`
	OccupantPhone pgtype.Text        `json:"occupant_phone"`
	OperatorName  pgtype.Text        `json:"operator_name"`
	OperatorPhone pgtype.Text        `json:"operator_phone"`
}

func (q *Queries) GetMe(ctx context.Context, id uuid.UUID) (GetMeRow, error) {
	row := q.db.QueryRow(ctx, getMe, id)
	var i GetMeRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.OccupantName,
		&i.OccupantPhone,
		&i.OperatorName,
		&i.OperatorPhone,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password, role, created_at, updated_at, deleted_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password, role, created_at, updated_at, deleted_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
