// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateOccupantDetails(ctx context.Context, arg CreateOccupantDetailsParams) (OccupantDetail, error)
	CreateOperatorDetails(ctx context.Context, arg CreateOperatorDetailsParams) (OperatorDetail, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error)
	GetMe(ctx context.Context, id uuid.UUID) (GetMeRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	UpdateOccupantDetails(ctx context.Context, arg UpdateOccupantDetailsParams) (OccupantDetail, error)
	UpdateOperatorDetails(ctx context.Context, arg UpdateOperatorDetailsParams) (OperatorDetail, error)
}

var _ Querier = (*Queries)(nil)
