// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduler.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkInvoiceExistsForPeriod = `-- name: CheckInvoiceExistsForPeriod :one
SELECT id FROM invoices 
WHERE room_id = $1 AND occupant_id = $2 AND waiting_for_room_vacant = false
  AND period_start < $4 AND period_end > $3 LIMIT 1
`

type CheckInvoiceExistsForPeriodParams struct {
	RoomID      uuid.UUID          `json:"room_id"`
	OccupantID  pgtype.UUID        `json:"occupant_id"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
}

func (q *Queries) CheckInvoiceExistsForPeriod(ctx context.Context, arg CheckInvoiceExistsForPeriodParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, checkInvoiceExistsForPeriod,
		arg.RoomID,
		arg.OccupantID,
		arg.PeriodEnd,
		arg.PeriodStart,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const countOccupiedRoomsForMonth = `-- name: CountOccupiedRoomsForMonth :one
SELECT COUNT(DISTINCT room_id) 
FROM invoices 
WHERE occupant_id IS NOT NULL 
  AND waiting_for_room_vacant = false 
  AND period_start <= $1 AND period_end >= $1
`

func (q *Queries) CountOccupiedRoomsForMonth(ctx context.Context, periodStart pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countOccupiedRoomsForMonth, periodStart)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTotalRooms = `-- name: CountTotalRooms :one
SELECT COUNT(id) FROM rooms
`

func (q *Queries) CountTotalRooms(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTotalRooms)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActiveInvoicesExpiringSoon = `-- name: GetActiveInvoicesExpiringSoon :many
SELECT i.id, i.room_id, i.occupant_id, i.period_end, r.price as room_price 
FROM invoices i
JOIN rooms r ON i.room_id = r.id
JOIN occupant_details od ON i.occupant_id = od.user_id
WHERE i.waiting_for_room_vacant = false 
  AND od.status = 'ACTIVE'
  AND i.period_end <= $1
  AND i.period_end >= CURRENT_TIMESTAMP
`

type GetActiveInvoicesExpiringSoonRow struct {
	ID         uuid.UUID          `json:"id"`
	RoomID     uuid.UUID          `json:"room_id"`
	OccupantID pgtype.UUID        `json:"occupant_id"`
	PeriodEnd  pgtype.Timestamptz `json:"period_end"`
	RoomPrice  pgtype.Numeric     `json:"room_price"`
}

func (q *Queries) GetActiveInvoicesExpiringSoon(ctx context.Context, periodEnd pgtype.Timestamptz) ([]GetActiveInvoicesExpiringSoonRow, error) {
	rows, err := q.db.Query(ctx, getActiveInvoicesExpiringSoon, periodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveInvoicesExpiringSoonRow
	for rows.Next() {
		var i GetActiveInvoicesExpiringSoonRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.OccupantID,
			&i.PeriodEnd,
			&i.RoomPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOccupancySnapshot = `-- name: UpsertOccupancySnapshot :exec
INSERT INTO room_occupancy_snapshots (year, month, total_rooms, occupied_rooms, snapshot_date)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (year, month) DO UPDATE 
SET total_rooms = EXCLUDED.total_rooms, 
    occupied_rooms = EXCLUDED.occupied_rooms, 
    snapshot_date = EXCLUDED.snapshot_date,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertOccupancySnapshotParams struct {
	Year          int32              `json:"year"`
	Month         int32              `json:"month"`
	TotalRooms    int32              `json:"total_rooms"`
	OccupiedRooms int32              `json:"occupied_rooms"`
	SnapshotDate  pgtype.Timestamptz `json:"snapshot_date"`
}

func (q *Queries) UpsertOccupancySnapshot(ctx context.Context, arg UpsertOccupancySnapshotParams) error {
	_, err := q.db.Exec(ctx, upsertOccupancySnapshot,
		arg.Year,
		arg.Month,
		arg.TotalRooms,
		arg.OccupiedRooms,
		arg.SnapshotDate,
	)
	return err
}
