// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOccupantDetails = `-- name: CreateOccupantDetails :one
INSERT INTO occupant_details (user_id, name, phone_number, address, occupation, status, move_in_date, move_out_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, user_id, name, phone_number, address, id_card_number, emergency_contact, status, move_in_date, move_out_date, created_at, updated_at, occupation
`

type CreateOccupantDetailsParams struct {
	UserID      uuid.UUID              `json:"user_id"`
	Name        string                 `json:"name"`
	PhoneNumber pgtype.Text            `json:"phone_number"`
	Address     pgtype.Text            `json:"address"`
	Occupation  OccupantOccupationEnum `json:"occupation"`
	Status      ProfileStatusEnum      `json:"status"`
	MoveInDate  pgtype.Timestamptz     `json:"move_in_date"`
	MoveOutDate pgtype.Timestamptz     `json:"move_out_date"`
}

func (q *Queries) CreateOccupantDetails(ctx context.Context, arg CreateOccupantDetailsParams) (OccupantDetail, error) {
	row := q.db.QueryRow(ctx, createOccupantDetails,
		arg.UserID,
		arg.Name,
		arg.PhoneNumber,
		arg.Address,
		arg.Occupation,
		arg.Status,
		arg.MoveInDate,
		arg.MoveOutDate,
	)
	var i OccupantDetail
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PhoneNumber,
		&i.Address,
		&i.IDCardNumber,
		&i.EmergencyContact,
		&i.Status,
		&i.MoveInDate,
		&i.MoveOutDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Occupation,
	)
	return i, err
}

const createOperatorDetails = `-- name: CreateOperatorDetails :one
INSERT INTO operator_details (user_id, name, phone_number, address, status)
VALUES ($1, $2, $3, $4, $5) RETURNING id, user_id, name, phone_number, address, status, created_at, updated_at
`

type CreateOperatorDetailsParams struct {
	UserID      uuid.UUID         `json:"user_id"`
	Name        string            `json:"name"`
	PhoneNumber string            `json:"phone_number"`
	Address     string            `json:"address"`
	Status      ProfileStatusEnum `json:"status"`
}

func (q *Queries) CreateOperatorDetails(ctx context.Context, arg CreateOperatorDetailsParams) (OperatorDetail, error) {
	row := q.db.QueryRow(ctx, createOperatorDetails,
		arg.UserID,
		arg.Name,
		arg.PhoneNumber,
		arg.Address,
		arg.Status,
	)
	var i OperatorDetail
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PhoneNumber,
		&i.Address,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT u.id, u.email, u.role, u.created_at, u.updated_at,
       o.id as occupant_id, o.name as occupant_name, o.phone_number as occupant_phone, 
       o.address as occupant_address, o.occupation as occupant_occupation, o.status as occupant_status,
       o.move_in_date as occupant_move_in, o.move_out_date as occupant_move_out,
       op.id as operator_id, op.name as operator_name, op.phone_number as operator_phone,
       op.address as operator_address, op.status as operator_status
FROM users u
LEFT JOIN occupant_details o ON u.id = o.user_id
LEFT JOIN operator_details op ON u.id = op.user_id
WHERE u.deleted_at IS NULL
ORDER BY u.created_at DESC
`

type GetAllUsersRow struct {
	ID                 uuid.UUID                  `json:"id"`
	Email              string                     `json:"email"`
	Role               RoleEnum                   `json:"role"`
	CreatedAt          pgtype.Timestamptz         `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz         `json:"updated_at"`
	OccupantID         pgtype.UUID                `json:"occupant_id"`
	OccupantName       pgtype.Text                `json:"occupant_name"`
	OccupantPhone      pgtype.Text                `json:"occupant_phone"`
	OccupantAddress    pgtype.Text                `json:"occupant_address"`
	OccupantOccupation NullOccupantOccupationEnum `json:"occupant_occupation"`
	OccupantStatus     NullProfileStatusEnum      `json:"occupant_status"`
	OccupantMoveIn     pgtype.Timestamptz         `json:"occupant_move_in"`
	OccupantMoveOut    pgtype.Timestamptz         `json:"occupant_move_out"`
	OperatorID         pgtype.UUID                `json:"operator_id"`
	OperatorName       pgtype.Text                `json:"operator_name"`
	OperatorPhone      pgtype.Text                `json:"operator_phone"`
	OperatorAddress    pgtype.Text                `json:"operator_address"`
	OperatorStatus     NullProfileStatusEnum      `json:"operator_status"`
}

func (q *Queries) GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUsersRow
	for rows.Next() {
		var i GetAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OccupantID,
			&i.OccupantName,
			&i.OccupantPhone,
			&i.OccupantAddress,
			&i.OccupantOccupation,
			&i.OccupantStatus,
			&i.OccupantMoveIn,
			&i.OccupantMoveOut,
			&i.OperatorID,
			&i.OperatorName,
			&i.OperatorPhone,
			&i.OperatorAddress,
			&i.OperatorStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users SET deleted_at = CURRENT_TIMESTAMP WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateOccupantDetails = `-- name: UpdateOccupantDetails :one
UPDATE occupant_details 
SET name = $2, phone_number = $3, address = $4, occupation = $5, status = $6, move_in_date = $7, move_out_date = $8, updated_at = CURRENT_TIMESTAMP
WHERE user_id = $1 RETURNING id, user_id, name, phone_number, address, id_card_number, emergency_contact, status, move_in_date, move_out_date, created_at, updated_at, occupation
`

type UpdateOccupantDetailsParams struct {
	UserID      uuid.UUID              `json:"user_id"`
	Name        string                 `json:"name"`
	PhoneNumber pgtype.Text            `json:"phone_number"`
	Address     pgtype.Text            `json:"address"`
	Occupation  OccupantOccupationEnum `json:"occupation"`
	Status      ProfileStatusEnum      `json:"status"`
	MoveInDate  pgtype.Timestamptz     `json:"move_in_date"`
	MoveOutDate pgtype.Timestamptz     `json:"move_out_date"`
}

func (q *Queries) UpdateOccupantDetails(ctx context.Context, arg UpdateOccupantDetailsParams) (OccupantDetail, error) {
	row := q.db.QueryRow(ctx, updateOccupantDetails,
		arg.UserID,
		arg.Name,
		arg.PhoneNumber,
		arg.Address,
		arg.Occupation,
		arg.Status,
		arg.MoveInDate,
		arg.MoveOutDate,
	)
	var i OccupantDetail
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PhoneNumber,
		&i.Address,
		&i.IDCardNumber,
		&i.EmergencyContact,
		&i.Status,
		&i.MoveInDate,
		&i.MoveOutDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Occupation,
	)
	return i, err
}

const updateOperatorDetails = `-- name: UpdateOperatorDetails :one
UPDATE operator_details 
SET name = $2, phone_number = $3, address = $4, status = $5, updated_at = CURRENT_TIMESTAMP
WHERE user_id = $1 RETURNING id, user_id, name, phone_number, address, status, created_at, updated_at
`

type UpdateOperatorDetailsParams struct {
	UserID      uuid.UUID         `json:"user_id"`
	Name        string            `json:"name"`
	PhoneNumber string            `json:"phone_number"`
	Address     string            `json:"address"`
	Status      ProfileStatusEnum `json:"status"`
}

func (q *Queries) UpdateOperatorDetails(ctx context.Context, arg UpdateOperatorDetailsParams) (OperatorDetail, error) {
	row := q.db.QueryRow(ctx, updateOperatorDetails,
		arg.UserID,
		arg.Name,
		arg.PhoneNumber,
		arg.Address,
		arg.Status,
	)
	var i OperatorDetail
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PhoneNumber,
		&i.Address,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
