// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ActivateOccupant(ctx context.Context, userID uuid.UUID) error
	ActivateReservation(ctx context.Context, id uuid.UUID) error
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	DeactivateOccupant(ctx context.Context, userID uuid.UUID) error
	DeleteRoom(ctx context.Context, id uuid.UUID) error
	GetActiveRoomOccupancy(ctx context.Context, roomID uuid.UUID) (Invoice, error)
	GetRoom(ctx context.Context, id uuid.UUID) (Room, error)
	GetWaitingReservation(ctx context.Context, roomID uuid.UUID) (Invoice, error)
	ListRooms(ctx context.Context) ([]Room, error)
	ListRoomsWithAssets(ctx context.Context) ([]ListRoomsWithAssetsRow, error)
	LockRoom(ctx context.Context, id uuid.UUID) (Room, error)
	LockUser(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	TruncateInvoicePeriod(ctx context.Context, id uuid.UUID) error
	UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error)
}

var _ Querier = (*Queries)(nil)
