// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: room.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateOccupant = `-- name: ActivateOccupant :exec
UPDATE occupant_details SET status = 'ACTIVE', move_in_date = CURRENT_TIMESTAMP, move_out_date = NULL WHERE user_id = $1
`

func (q *Queries) ActivateOccupant(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, activateOccupant, userID)
	return err
}

const activateReservation = `-- name: ActivateReservation :exec
UPDATE invoices 
SET waiting_for_room_vacant = false, is_dp_reservation = false, prior_occupant_id = NULL 
WHERE id = $1
`

func (q *Queries) ActivateReservation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, activateReservation, id)
	return err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (name, price, status)
VALUES ($1, $2, $3) RETURNING id, name, price, status, created_at, updated_at
`

type CreateRoomParams struct {
	Name   string         `json:"name"`
	Price  pgtype.Numeric `json:"price"`
	Status RoomStatusEnum `json:"status"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom, arg.Name, arg.Price, arg.Status)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateOccupant = `-- name: DeactivateOccupant :exec
UPDATE occupant_details SET status = 'INACTIVE', move_out_date = CURRENT_TIMESTAMP WHERE user_id = $1
`

func (q *Queries) DeactivateOccupant(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateOccupant, userID)
	return err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM rooms WHERE id = $1
`

func (q *Queries) DeleteRoom(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoom, id)
	return err
}

const getActiveRoomOccupancy = `-- name: GetActiveRoomOccupancy :one
SELECT id, room_id, occupant_id, price_applied, paid_nominal, period_start, period_end, status, note, created_at, updated_at, import_code, is_dp_reservation, waiting_for_room_vacant, prior_occupant_id FROM invoices 
WHERE room_id = $1 AND period_end > CURRENT_TIMESTAMP AND waiting_for_room_vacant = false
ORDER BY period_start ASC LIMIT 1
`

func (q *Queries) GetActiveRoomOccupancy(ctx context.Context, roomID uuid.UUID) (Invoice, error) {
	row := q.db.QueryRow(ctx, getActiveRoomOccupancy, roomID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.OccupantID,
		&i.PriceApplied,
		&i.PaidNominal,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImportCode,
		&i.IsDpReservation,
		&i.WaitingForRoomVacant,
		&i.PriorOccupantID,
	)
	return i, err
}

const getRoom = `-- name: GetRoom :one
SELECT id, name, price, status, created_at, updated_at FROM rooms
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRoom(ctx context.Context, id uuid.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoom, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWaitingReservation = `-- name: GetWaitingReservation :one
SELECT id, room_id, occupant_id, price_applied, paid_nominal, period_start, period_end, status, note, created_at, updated_at, import_code, is_dp_reservation, waiting_for_room_vacant, prior_occupant_id FROM invoices 
WHERE room_id = $1 AND waiting_for_room_vacant = true AND is_dp_reservation = true AND period_end > CURRENT_TIMESTAMP
ORDER BY period_start ASC LIMIT 1
`

func (q *Queries) GetWaitingReservation(ctx context.Context, roomID uuid.UUID) (Invoice, error) {
	row := q.db.QueryRow(ctx, getWaitingReservation, roomID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.OccupantID,
		&i.PriceApplied,
		&i.PaidNominal,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImportCode,
		&i.IsDpReservation,
		&i.WaitingForRoomVacant,
		&i.PriorOccupantID,
	)
	return i, err
}

const listRooms = `-- name: ListRooms :many
SELECT id, name, price, status, created_at, updated_at FROM rooms
ORDER BY name ASC
`

func (q *Queries) ListRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomsWithAssets = `-- name: ListRoomsWithAssets :many
SELECT 
    r.id, r.name, r.status, r.price, r.created_at, r.updated_at,
    COALESCE(
        (SELECT json_agg(json_build_object(
                        'id', a.id,
            'assetMasterId', a.asset_master_id,
            'name', m.name,
            'details', a.details,
            'status', a.status,
            'roomId', a.room_id,
            'assetMaster', json_build_object(
                'id', m.id,
                'name', m.name
            )
        ))
        FROM assets a
        JOIN asset_masters m ON a.asset_master_id = m.id
        WHERE a.room_id = r.id), 
        '[]'::json
    )::json as assets,
    (SELECT COUNT(*) FROM invoices WHERE room_id = r.id) as invoices_count,
    (SELECT COUNT(*) FROM invoices i JOIN payments p ON i.id = p.id WHERE i.room_id = r.id) as payments_count,
    (SELECT json_build_object('id', u.id, 'email', u.email, 'name', od.name)
     FROM occupant_details od 
     JOIN users u ON od.user_id = u.id 
     JOIN invoices i ON i.occupant_id = u.id
     WHERE i.room_id = r.id AND od.status = 'ACTIVE' LIMIT 1
    )::json as active_occupant
FROM rooms r
ORDER BY r.name ASC
`

type ListRoomsWithAssetsRow struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	Status         RoomStatusEnum     `json:"status"`
	Price          pgtype.Numeric     `json:"price"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Assets         []byte             `json:"assets"`
	InvoicesCount  int64              `json:"invoices_count"`
	PaymentsCount  int64              `json:"payments_count"`
	ActiveOccupant []byte             `json:"active_occupant"`
}

func (q *Queries) ListRoomsWithAssets(ctx context.Context) ([]ListRoomsWithAssetsRow, error) {
	rows, err := q.db.Query(ctx, listRoomsWithAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomsWithAssetsRow
	for rows.Next() {
		var i ListRoomsWithAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Assets,
			&i.InvoicesCount,
			&i.PaymentsCount,
			&i.ActiveOccupant,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRoom = `-- name: LockRoom :one
SELECT id, name, price, status, created_at, updated_at FROM rooms WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockRoom(ctx context.Context, id uuid.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, lockRoom, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockUser = `-- name: LockUser :one
SELECT id FROM users WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockUser(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockUser, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const truncateInvoicePeriod = `-- name: TruncateInvoicePeriod :exec
UPDATE invoices SET period_end = CURRENT_TIMESTAMP WHERE id = $1
`

func (q *Queries) TruncateInvoicePeriod(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, truncateInvoicePeriod, id)
	return err
}

const updateRoom = `-- name: UpdateRoom :one
UPDATE rooms 
SET name = $2, price = $3, status = $4, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 RETURNING id, name, price, status, created_at, updated_at
`

type UpdateRoomParams struct {
	ID     uuid.UUID      `json:"id"`
	Name   string         `json:"name"`
	Price  pgtype.Numeric `json:"price"`
	Status RoomStatusEnum `json:"status"`
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoom,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.Status,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
