version: '3.8'

services:
  postgres:
    image: docker.io/library/postgres:15-alpine
    container_name: kost_postgres
    restart: always
    environment:
      POSTGRES_DB: kost_db
      POSTGRES_USER: kost_user
      POSTGRES_PASSWORD: kost_password
    ports:
      - "5432:5432"
    volumes:
      - kost_pg_data:/var/lib/postgresql/data

volumes:
  kost_pg_data:
