// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ComplaintCategoryEnum string

const (
	ComplaintCategoryEnumASSET  ComplaintCategoryEnum = "ASSET"
	ComplaintCategoryEnumOTHERS ComplaintCategoryEnum = "OTHERS"
)

func (e *ComplaintCategoryEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ComplaintCategoryEnum(s)
	case string:
		*e = ComplaintCategoryEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ComplaintCategoryEnum: %T", src)
	}
	return nil
}

type NullComplaintCategoryEnum struct {
	ComplaintCategoryEnum ComplaintCategoryEnum `json:"complaint_category_enum"`
	Valid                 bool                  `json:"valid"` // Valid is true if ComplaintCategoryEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullComplaintCategoryEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ComplaintCategoryEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ComplaintCategoryEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullComplaintCategoryEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ComplaintCategoryEnum), nil
}

type ComplaintStatusEnum string

const (
	ComplaintStatusEnumPENDING   ComplaintStatusEnum = "PENDING"
	ComplaintStatusEnumPROCESSED ComplaintStatusEnum = "PROCESSED"
	ComplaintStatusEnumRESOLVED  ComplaintStatusEnum = "RESOLVED"
)

func (e *ComplaintStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ComplaintStatusEnum(s)
	case string:
		*e = ComplaintStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ComplaintStatusEnum: %T", src)
	}
	return nil
}

type NullComplaintStatusEnum struct {
	ComplaintStatusEnum ComplaintStatusEnum `json:"complaint_status_enum"`
	Valid               bool                `json:"valid"` // Valid is true if ComplaintStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullComplaintStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ComplaintStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ComplaintStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullComplaintStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ComplaintStatusEnum), nil
}

type ExpenseCategoryEnum string

const (
	ExpenseCategoryEnumASSETREPAIR ExpenseCategoryEnum = "ASSET_REPAIR"
	ExpenseCategoryEnumLISTRIK     ExpenseCategoryEnum = "LISTRIK"
	ExpenseCategoryEnumGAJIPRT     ExpenseCategoryEnum = "GAJI_PRT"
	ExpenseCategoryEnumOPSDAPUR    ExpenseCategoryEnum = "OPS_DAPUR"
	ExpenseCategoryEnumBTN         ExpenseCategoryEnum = "BTN"
	ExpenseCategoryEnumINTERNET    ExpenseCategoryEnum = "INTERNET"
	ExpenseCategoryEnumLAINLAIN    ExpenseCategoryEnum = "LAIN_LAIN"
)

func (e *ExpenseCategoryEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExpenseCategoryEnum(s)
	case string:
		*e = ExpenseCategoryEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ExpenseCategoryEnum: %T", src)
	}
	return nil
}

type NullExpenseCategoryEnum struct {
	ExpenseCategoryEnum ExpenseCategoryEnum `json:"expense_category_enum"`
	Valid               bool                `json:"valid"` // Valid is true if ExpenseCategoryEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExpenseCategoryEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ExpenseCategoryEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExpenseCategoryEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExpenseCategoryEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExpenseCategoryEnum), nil
}

type MaintenanceStatusEnum string

const (
	MaintenanceStatusEnumPROCESS  MaintenanceStatusEnum = "PROCESS"
	MaintenanceStatusEnumPENDING  MaintenanceStatusEnum = "PENDING"
	MaintenanceStatusEnumFINISHED MaintenanceStatusEnum = "FINISHED"
)

func (e *MaintenanceStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MaintenanceStatusEnum(s)
	case string:
		*e = MaintenanceStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for MaintenanceStatusEnum: %T", src)
	}
	return nil
}

type NullMaintenanceStatusEnum struct {
	MaintenanceStatusEnum MaintenanceStatusEnum `json:"maintenance_status_enum"`
	Valid                 bool                  `json:"valid"` // Valid is true if MaintenanceStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMaintenanceStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.MaintenanceStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MaintenanceStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMaintenanceStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MaintenanceStatusEnum), nil
}

type OccupantOccupationEnum string

const (
	OccupantOccupationEnumBEKERJA OccupantOccupationEnum = "BEKERJA"
	OccupantOccupationEnumKULIAH  OccupantOccupationEnum = "KULIAH"
)

func (e *OccupantOccupationEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OccupantOccupationEnum(s)
	case string:
		*e = OccupantOccupationEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for OccupantOccupationEnum: %T", src)
	}
	return nil
}

type NullOccupantOccupationEnum struct {
	OccupantOccupationEnum OccupantOccupationEnum `json:"occupant_occupation_enum"`
	Valid                  bool                   `json:"valid"` // Valid is true if OccupantOccupationEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOccupantOccupationEnum) Scan(value interface{}) error {
	if value == nil {
		ns.OccupantOccupationEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OccupantOccupationEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOccupantOccupationEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OccupantOccupationEnum), nil
}

type PaymentMethodEnum string

const (
	PaymentMethodEnumTRANSFER PaymentMethodEnum = "TRANSFER"
	PaymentMethodEnumQRIS     PaymentMethodEnum = "QRIS"
	PaymentMethodEnumEWALLET  PaymentMethodEnum = "E_WALLET"
	PaymentMethodEnumCASH     PaymentMethodEnum = "CASH"
)

func (e *PaymentMethodEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethodEnum(s)
	case string:
		*e = PaymentMethodEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethodEnum: %T", src)
	}
	return nil
}

type NullPaymentMethodEnum struct {
	PaymentMethodEnum PaymentMethodEnum `json:"payment_method_enum"`
	Valid             bool              `json:"valid"` // Valid is true if PaymentMethodEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethodEnum) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethodEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethodEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethodEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethodEnum), nil
}

type PaymentStatusEnum string

const (
	PaymentStatusEnumPAID    PaymentStatusEnum = "PAID"
	PaymentStatusEnumUNPAID  PaymentStatusEnum = "UNPAID"
	PaymentStatusEnumOVERDUE PaymentStatusEnum = "OVERDUE"
)

func (e *PaymentStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatusEnum(s)
	case string:
		*e = PaymentStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatusEnum: %T", src)
	}
	return nil
}

type NullPaymentStatusEnum struct {
	PaymentStatusEnum PaymentStatusEnum `json:"payment_status_enum"`
	Valid             bool              `json:"valid"` // Valid is true if PaymentStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatusEnum), nil
}

type ProfileStatusEnum string

const (
	ProfileStatusEnumACTIVE   ProfileStatusEnum = "ACTIVE"
	ProfileStatusEnumINACTIVE ProfileStatusEnum = "INACTIVE"
)

func (e *ProfileStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProfileStatusEnum(s)
	case string:
		*e = ProfileStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ProfileStatusEnum: %T", src)
	}
	return nil
}

type NullProfileStatusEnum struct {
	ProfileStatusEnum ProfileStatusEnum `json:"profile_status_enum"`
	Valid             bool              `json:"valid"` // Valid is true if ProfileStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProfileStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ProfileStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProfileStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProfileStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProfileStatusEnum), nil
}

type RoleEnum string

const (
	RoleEnumADMIN    RoleEnum = "ADMIN"
	RoleEnumOPERATOR RoleEnum = "OPERATOR"
	RoleEnumOCCUPANT RoleEnum = "OCCUPANT"
)

func (e *RoleEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoleEnum(s)
	case string:
		*e = RoleEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for RoleEnum: %T", src)
	}
	return nil
}

type NullRoleEnum struct {
	RoleEnum RoleEnum `json:"role_enum"`
	Valid    bool     `json:"valid"` // Valid is true if RoleEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoleEnum) Scan(value interface{}) error {
	if value == nil {
		ns.RoleEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoleEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoleEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoleEnum), nil
}

type RoomStatusEnum string

const (
	RoomStatusEnumVACANT      RoomStatusEnum = "VACANT"
	RoomStatusEnumOCCUPIED    RoomStatusEnum = "OCCUPIED"
	RoomStatusEnumMAINTENANCE RoomStatusEnum = "MAINTENANCE"
)

func (e *RoomStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoomStatusEnum(s)
	case string:
		*e = RoomStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for RoomStatusEnum: %T", src)
	}
	return nil
}

type NullRoomStatusEnum struct {
	RoomStatusEnum RoomStatusEnum `json:"room_status_enum"`
	Valid          bool           `json:"valid"` // Valid is true if RoomStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoomStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.RoomStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoomStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoomStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoomStatusEnum), nil
}

type TransactionTypeEnum string

const (
	TransactionTypeEnumINCOME  TransactionTypeEnum = "INCOME"
	TransactionTypeEnumEXPENSE TransactionTypeEnum = "EXPENSE"
)

func (e *TransactionTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionTypeEnum(s)
	case string:
		*e = TransactionTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionTypeEnum: %T", src)
	}
	return nil
}

type NullTransactionTypeEnum struct {
	TransactionTypeEnum TransactionTypeEnum `json:"transaction_type_enum"`
	Valid               bool                `json:"valid"` // Valid is true if TransactionTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionTypeEnum), nil
}

type Asset struct {
	ID            uuid.UUID          `json:"id"`
	AssetMasterID uuid.UUID          `json:"asset_master_id"`
	RoomID        uuid.UUID          `json:"room_id"`
	Name          string             `json:"name"`
	Details       pgtype.Text        `json:"details"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type AssetMaintenanceLog struct {
	ID        uuid.UUID             `json:"id"`
	AssetID   uuid.UUID             `json:"asset_id"`
	Details   string                `json:"details"`
	Status    MaintenanceStatusEnum `json:"status"`
	CreatedAt pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt pgtype.Timestamptz    `json:"updated_at"`
}

type AssetMaster struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Complaint struct {
	ID           uuid.UUID             `json:"id"`
	Category     ComplaintCategoryEnum `json:"category"`
	Detail       string                `json:"detail"`
	Status       ComplaintStatusEnum   `json:"status"`
	ReportedByID uuid.UUID             `json:"reported_by_id"`
	AssetID      pgtype.UUID           `json:"asset_id"`
	CreatedAt    pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz    `json:"updated_at"`
}

type FinancialRecord struct {
	ID              uuid.UUID               `json:"id"`
	Type            TransactionTypeEnum     `json:"type"`
	Amount          pgtype.Numeric          `json:"amount"`
	Description     pgtype.Text             `json:"description"`
	PaymentID       pgtype.UUID             `json:"payment_id"`
	CreatedAt       pgtype.Timestamptz      `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz      `json:"updated_at"`
	Date            pgtype.Timestamptz      `json:"date"`
	AssetID         pgtype.UUID             `json:"asset_id"`
	ExpenseCategory NullExpenseCategoryEnum `json:"expense_category"`
}

type Invoice struct {
	ID                   uuid.UUID          `json:"id"`
	RoomID               uuid.UUID          `json:"room_id"`
	OccupantID           pgtype.UUID        `json:"occupant_id"`
	PriceApplied         pgtype.Numeric     `json:"price_applied"`
	PaidNominal          pgtype.Numeric     `json:"paid_nominal"`
	PeriodStart          pgtype.Timestamptz `json:"period_start"`
	PeriodEnd            pgtype.Timestamptz `json:"period_end"`
	Status               PaymentStatusEnum  `json:"status"`
	Note                 pgtype.Text        `json:"note"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	ImportCode           pgtype.Text        `json:"import_code"`
	IsDpReservation      bool               `json:"is_dp_reservation"`
	WaitingForRoomVacant bool               `json:"waiting_for_room_vacant"`
	PriorOccupantID      pgtype.UUID        `json:"prior_occupant_id"`
}

type InvoicePayment struct {
	ID            uuid.UUID          `json:"id"`
	InvoiceID     uuid.UUID          `json:"invoice_id"`
	PaymentID     uuid.UUID          `json:"payment_id"`
	AmountApplied pgtype.Numeric     `json:"amount_applied"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type OccupantDetail struct {
	ID               uuid.UUID              `json:"id"`
	UserID           uuid.UUID              `json:"user_id"`
	Name             string                 `json:"name"`
	PhoneNumber      pgtype.Text            `json:"phone_number"`
	Address          pgtype.Text            `json:"address"`
	IDCardNumber     pgtype.Text            `json:"id_card_number"`
	EmergencyContact pgtype.Text            `json:"emergency_contact"`
	Status           ProfileStatusEnum      `json:"status"`
	MoveInDate       pgtype.Timestamptz     `json:"move_in_date"`
	MoveOutDate      pgtype.Timestamptz     `json:"move_out_date"`
	CreatedAt        pgtype.Timestamptz     `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz     `json:"updated_at"`
	Occupation       OccupantOccupationEnum `json:"occupation"`
}

type OperatorDetail struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	Name        string             `json:"name"`
	PhoneNumber string             `json:"phone_number"`
	Address     string             `json:"address"`
	Status      ProfileStatusEnum  `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Payment struct {
	ID            uuid.UUID          `json:"id"`
	OccupantID    uuid.UUID          `json:"occupant_id"`
	Amount        pgtype.Numeric     `json:"amount"`
	Note          pgtype.Text        `json:"note"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	ImportCode    pgtype.Text        `json:"import_code"`
	PaymentDate   pgtype.Timestamptz `json:"payment_date"`
	PaymentMethod PaymentMethodEnum  `json:"payment_method"`
}

type Room struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Price     pgtype.Numeric     `json:"price"`
	Status    RoomStatusEnum     `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RoomOccupancySnapshot struct {
	ID            uuid.UUID          `json:"id"`
	Year          int32              `json:"year"`
	Month         int32              `json:"month"`
	OccupiedRooms int32              `json:"occupied_rooms"`
	TotalRooms    int32              `json:"total_rooms"`
	SnapshotDate  pgtype.Timestamptz `json:"snapshot_date"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	Role      RoleEnum           `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}
