// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: occupant.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getOccupantDetail = `-- name: GetOccupantDetail :one
SELECT u.email, o.id, o.user_id, o.name, o.phone_number, o.address, o.id_card_number, o.emergency_contact, o.status, o.move_in_date, o.move_out_date, o.created_at, o.updated_at, o.occupation 
FROM users u
JOIN occupant_details o ON u.id = o.user_id
WHERE u.id = $1 LIMIT 1
`

type GetOccupantDetailRow struct {
	Email            string                 `json:"email"`
	ID               uuid.UUID              `json:"id"`
	UserID           uuid.UUID              `json:"user_id"`
	Name             string                 `json:"name"`
	PhoneNumber      pgtype.Text            `json:"phone_number"`
	Address          pgtype.Text            `json:"address"`
	IDCardNumber     pgtype.Text            `json:"id_card_number"`
	EmergencyContact pgtype.Text            `json:"emergency_contact"`
	Status           ProfileStatusEnum      `json:"status"`
	MoveInDate       pgtype.Timestamptz     `json:"move_in_date"`
	MoveOutDate      pgtype.Timestamptz     `json:"move_out_date"`
	CreatedAt        pgtype.Timestamptz     `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz     `json:"updated_at"`
	Occupation       OccupantOccupationEnum `json:"occupation"`
}

func (q *Queries) GetOccupantDetail(ctx context.Context, id uuid.UUID) (GetOccupantDetailRow, error) {
	row := q.db.QueryRow(ctx, getOccupantDetail, id)
	var i GetOccupantDetailRow
	err := row.Scan(
		&i.Email,
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PhoneNumber,
		&i.Address,
		&i.IDCardNumber,
		&i.EmergencyContact,
		&i.Status,
		&i.MoveInDate,
		&i.MoveOutDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Occupation,
	)
	return i, err
}

const listOccupants = `-- name: ListOccupants :many
SELECT u.id, u.email, o.name, o.phone_number, o.status, o.move_in_date 
FROM users u
JOIN occupant_details o ON u.id = o.user_id
WHERE u.role = 'OCCUPANT'
ORDER BY o.name ASC
`

type ListOccupantsRow struct {
	ID          uuid.UUID          `json:"id"`
	Email       string             `json:"email"`
	Name        string             `json:"name"`
	PhoneNumber pgtype.Text        `json:"phone_number"`
	Status      ProfileStatusEnum  `json:"status"`
	MoveInDate  pgtype.Timestamptz `json:"move_in_date"`
}

func (q *Queries) ListOccupants(ctx context.Context) ([]ListOccupantsRow, error) {
	rows, err := q.db.Query(ctx, listOccupants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOccupantsRow
	for rows.Next() {
		var i ListOccupantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.PhoneNumber,
			&i.Status,
			&i.MoveInDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
