// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CheckInvoiceExistsForPeriod(ctx context.Context, arg CheckInvoiceExistsForPeriodParams) (uuid.UUID, error)
	CountOccupiedRoomsForMonth(ctx context.Context, periodStart pgtype.Timestamptz) (int64, error)
	CountTotalRooms(ctx context.Context) (int64, error)
	CreateAutoInvoice(ctx context.Context, arg CreateAutoInvoiceParams) error
	GetActiveInvoicesExpiringSoon(ctx context.Context, periodEnd pgtype.Timestamptz) ([]GetActiveInvoicesExpiringSoonRow, error)
	UpsertOccupancySnapshot(ctx context.Context, arg UpsertOccupancySnapshotParams) error
}

var _ Querier = (*Queries)(nil)
