apiVersion: apps/v1
kind: Deployment
metadata:
  name: kost-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kost-frontend
  template:
    metadata:
      labels:
        app: kost-frontend
    spec:
      containers:
        - name: kost-frontend
          image: ghcr.io/USERNAME_GITHUB/REPO-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "https://api.coliving.nabilbuilds.my.id"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: kost-frontend-service
spec:
  type: NodePort
  selector:
    app: kost-frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30301
