// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: complaints.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createComplaint = `-- name: CreateComplaint :one
INSERT INTO complaints (category, detail, status, reported_by_id, asset_id)
VALUES ($1, $2, $3, $4, $5) RETURNING id, category, detail, status, reported_by_id, asset_id, created_at, updated_at
`

type CreateComplaintParams struct {
	Category     ComplaintCategoryEnum `json:"category"`
	Detail       string                `json:"detail"`
	Status       ComplaintStatusEnum   `json:"status"`
	ReportedByID uuid.UUID             `json:"reported_by_id"`
	AssetID      pgtype.UUID           `json:"asset_id"`
}

func (q *Queries) CreateComplaint(ctx context.Context, arg CreateComplaintParams) (Complaint, error) {
	row := q.db.QueryRow(ctx, createComplaint,
		arg.Category,
		arg.Detail,
		arg.Status,
		arg.ReportedByID,
		arg.AssetID,
	)
	var i Complaint
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Detail,
		&i.Status,
		&i.ReportedByID,
		&i.AssetID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllComplaints = `-- name: GetAllComplaints :many
SELECT c.id, c.category, c.detail, c.status, c.reported_by_id, c.asset_id, c.created_at, c.updated_at, u.email as reporter_email, o.name as reporter_name, a.name as asset_name, r.name as room_name
FROM complaints c
JOIN users u ON c.reported_by_id = u.id
LEFT JOIN occupant_details o ON u.id = o.user_id
LEFT JOIN assets a ON c.asset_id = a.id
LEFT JOIN rooms r ON a.room_id = r.id
ORDER BY c.created_at DESC
`

type GetAllComplaintsRow struct {
	ID            uuid.UUID             `json:"id"`
	Category      ComplaintCategoryEnum `json:"category"`
	Detail        string                `json:"detail"`
	Status        ComplaintStatusEnum   `json:"status"`
	ReportedByID  uuid.UUID             `json:"reported_by_id"`
	AssetID       pgtype.UUID           `json:"asset_id"`
	CreatedAt     pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz    `json:"updated_at"`
	ReporterEmail string                `json:"reporter_email"`
	ReporterName  pgtype.Text           `json:"reporter_name"`
	AssetName     pgtype.Text           `json:"asset_name"`
	RoomName      pgtype.Text           `json:"room_name"`
}

func (q *Queries) GetAllComplaints(ctx context.Context) ([]GetAllComplaintsRow, error) {
	rows, err := q.db.Query(ctx, getAllComplaints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllComplaintsRow
	for rows.Next() {
		var i GetAllComplaintsRow
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Detail,
			&i.Status,
			&i.ReportedByID,
			&i.AssetID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReporterEmail,
			&i.ReporterName,
			&i.AssetName,
			&i.RoomName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getComplaintsByReporter = `-- name: GetComplaintsByReporter :many
SELECT c.id, c.category, c.detail, c.status, c.reported_by_id, c.asset_id, c.created_at, c.updated_at, a.name as asset_name
FROM complaints c
LEFT JOIN assets a ON c.asset_id = a.id
WHERE c.reported_by_id = $1
ORDER BY c.created_at DESC
`

type GetComplaintsByReporterRow struct {
	ID           uuid.UUID             `json:"id"`
	Category     ComplaintCategoryEnum `json:"category"`
	Detail       string                `json:"detail"`
	Status       ComplaintStatusEnum   `json:"status"`
	ReportedByID uuid.UUID             `json:"reported_by_id"`
	AssetID      pgtype.UUID           `json:"asset_id"`
	CreatedAt    pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz    `json:"updated_at"`
	AssetName    pgtype.Text           `json:"asset_name"`
}

func (q *Queries) GetComplaintsByReporter(ctx context.Context, reportedByID uuid.UUID) ([]GetComplaintsByReporterRow, error) {
	rows, err := q.db.Query(ctx, getComplaintsByReporter, reportedByID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetComplaintsByReporterRow
	for rows.Next() {
		var i GetComplaintsByReporterRow
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Detail,
			&i.Status,
			&i.ReportedByID,
			&i.AssetID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssetName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOccupantCurrentRoomAssets = `-- name: GetOccupantCurrentRoomAssets :many
SELECT a.id, a.asset_master_id, a.room_id, a.name, a.details, a.status, a.created_at, a.updated_at, r.name as room_name, m.name as master_name
FROM assets a
JOIN rooms r ON a.room_id = r.id
JOIN asset_masters m ON a.asset_master_id = m.id
JOIN invoices i ON i.room_id = r.id
WHERE i.occupant_id = $1
  AND i.waiting_for_room_vacant = false
  AND i.period_end > CURRENT_TIMESTAMP
ORDER BY a.name ASC
`

type GetOccupantCurrentRoomAssetsRow struct {
	ID            uuid.UUID          `json:"id"`
	AssetMasterID uuid.UUID          `json:"asset_master_id"`
	RoomID        uuid.UUID          `json:"room_id"`
	Name          string             `json:"name"`
	Details       pgtype.Text        `json:"details"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	RoomName      string             `json:"room_name"`
	MasterName    string             `json:"master_name"`
}

func (q *Queries) GetOccupantCurrentRoomAssets(ctx context.Context, occupantID pgtype.UUID) ([]GetOccupantCurrentRoomAssetsRow, error) {
	rows, err := q.db.Query(ctx, getOccupantCurrentRoomAssets, occupantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOccupantCurrentRoomAssetsRow
	for rows.Next() {
		var i GetOccupantCurrentRoomAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.AssetMasterID,
			&i.RoomID,
			&i.Name,
			&i.Details,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RoomName,
			&i.MasterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComplaintStatus = `-- name: UpdateComplaintStatus :one
UPDATE complaints 
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 RETURNING id, category, detail, status, reported_by_id, asset_id, created_at, updated_at
`

type UpdateComplaintStatusParams struct {
	ID     uuid.UUID           `json:"id"`
	Status ComplaintStatusEnum `json:"status"`
}

func (q *Queries) UpdateComplaintStatus(ctx context.Context, arg UpdateComplaintStatusParams) (Complaint, error) {
	row := q.db.QueryRow(ctx, updateComplaintStatus, arg.ID, arg.Status)
	var i Complaint
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Detail,
		&i.Status,
		&i.ReportedByID,
		&i.AssetID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
