// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateComplaint(ctx context.Context, arg CreateComplaintParams) (Complaint, error)
	GetAllComplaints(ctx context.Context) ([]GetAllComplaintsRow, error)
	GetComplaintsByReporter(ctx context.Context, reportedByID uuid.UUID) ([]GetComplaintsByReporterRow, error)
	GetOccupantCurrentRoomAssets(ctx context.Context, occupantID pgtype.UUID) ([]GetOccupantCurrentRoomAssetsRow, error)
	UpdateComplaintStatus(ctx context.Context, arg UpdateComplaintStatusParams) (Complaint, error)
}

var _ Querier = (*Queries)(nil)
