// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: asset.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAssetMaster = `-- name: CreateAssetMaster :one
INSERT INTO asset_masters (name) VALUES ($1) RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateAssetMaster(ctx context.Context, name string) (AssetMaster, error) {
	row := q.db.QueryRow(ctx, createAssetMaster, name)
	var i AssetMaster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMaintenanceLog = `-- name: CreateMaintenanceLog :one
INSERT INTO asset_maintenance_log (asset_id, details, status)
VALUES ($1, $2, $3) RETURNING id, asset_id, details, status, created_at, updated_at
`

type CreateMaintenanceLogParams struct {
	AssetID uuid.UUID             `json:"asset_id"`
	Details string                `json:"details"`
	Status  MaintenanceStatusEnum `json:"status"`
}

func (q *Queries) CreateMaintenanceLog(ctx context.Context, arg CreateMaintenanceLogParams) (AssetMaintenanceLog, error) {
	row := q.db.QueryRow(ctx, createMaintenanceLog, arg.AssetID, arg.Details, arg.Status)
	var i AssetMaintenanceLog
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.Details,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAssetMaster = `-- name: DeleteAssetMaster :exec
DELETE FROM asset_masters WHERE id = $1
`

func (q *Queries) DeleteAssetMaster(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAssetMaster, id)
	return err
}

const deleteMaintenanceLog = `-- name: DeleteMaintenanceLog :exec
DELETE FROM asset_maintenance_log WHERE id = $1
`

func (q *Queries) DeleteMaintenanceLog(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMaintenanceLog, id)
	return err
}

const getMaintenanceLogsByAssetId = `-- name: GetMaintenanceLogsByAssetId :many
SELECT id, asset_id, details, status, created_at, updated_at FROM asset_maintenance_log WHERE asset_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetMaintenanceLogsByAssetId(ctx context.Context, assetID uuid.UUID) ([]AssetMaintenanceLog, error) {
	rows, err := q.db.Query(ctx, getMaintenanceLogsByAssetId, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssetMaintenanceLog
	for rows.Next() {
		var i AssetMaintenanceLog
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.Details,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetMasters = `-- name: ListAssetMasters :many
SELECT 
    am.id, am.name, am.created_at, am.updated_at,
    (SELECT COUNT(*) FROM assets a WHERE a.asset_master_id = am.id) as assets_count
FROM asset_masters am
ORDER BY am.name ASC
`

type ListAssetMastersRow struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	AssetsCount int64              `json:"assets_count"`
}

func (q *Queries) ListAssetMasters(ctx context.Context) ([]ListAssetMastersRow, error) {
	rows, err := q.db.Query(ctx, listAssetMasters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetMastersRow
	for rows.Next() {
		var i ListAssetMastersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssetsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssets = `-- name: ListAssets :many
SELECT a.id, a.asset_master_id, a.room_id, a.name, a.details, a.status, a.created_at, a.updated_at, m.name as master_name
FROM assets a
JOIN asset_masters m ON a.asset_master_id = m.id
ORDER BY a.created_at DESC
`

type ListAssetsRow struct {
	ID            uuid.UUID          `json:"id"`
	AssetMasterID uuid.UUID          `json:"asset_master_id"`
	RoomID        uuid.UUID          `json:"room_id"`
	Name          string             `json:"name"`
	Details       pgtype.Text        `json:"details"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	MasterName    string             `json:"master_name"`
}

func (q *Queries) ListAssets(ctx context.Context) ([]ListAssetsRow, error) {
	rows, err := q.db.Query(ctx, listAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetsRow
	for rows.Next() {
		var i ListAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.AssetMasterID,
			&i.RoomID,
			&i.Name,
			&i.Details,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MasterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsByRoom = `-- name: ListAssetsByRoom :many
SELECT a.id, a.asset_master_id, a.room_id, a.name, a.details, a.status, a.created_at, a.updated_at, m.name as master_name
FROM assets a
JOIN asset_masters m ON a.asset_master_id = m.id
WHERE a.room_id = $1
ORDER BY a.created_at DESC
`

type ListAssetsByRoomRow struct {
	ID            uuid.UUID          `json:"id"`
	AssetMasterID uuid.UUID          `json:"asset_master_id"`
	RoomID        uuid.UUID          `json:"room_id"`
	Name          string             `json:"name"`
	Details       pgtype.Text        `json:"details"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	MasterName    string             `json:"master_name"`
}

func (q *Queries) ListAssetsByRoom(ctx context.Context, roomID uuid.UUID) ([]ListAssetsByRoomRow, error) {
	rows, err := q.db.Query(ctx, listAssetsByRoom, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetsByRoomRow
	for rows.Next() {
		var i ListAssetsByRoomRow
		if err := rows.Scan(
			&i.ID,
			&i.AssetMasterID,
			&i.RoomID,
			&i.Name,
			&i.Details,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MasterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssetMaster = `-- name: UpdateAssetMaster :one
UPDATE asset_masters SET name = $2 WHERE id = $1 RETURNING id, name, created_at, updated_at
`

type UpdateAssetMasterParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateAssetMaster(ctx context.Context, arg UpdateAssetMasterParams) (AssetMaster, error) {
	row := q.db.QueryRow(ctx, updateAssetMaster, arg.ID, arg.Name)
	var i AssetMaster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMaintenanceLog = `-- name: UpdateMaintenanceLog :one
UPDATE asset_maintenance_log 
SET details = $2, status = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 RETURNING id, asset_id, details, status, created_at, updated_at
`

type UpdateMaintenanceLogParams struct {
	ID      uuid.UUID             `json:"id"`
	Details string                `json:"details"`
	Status  MaintenanceStatusEnum `json:"status"`
}

func (q *Queries) UpdateMaintenanceLog(ctx context.Context, arg UpdateMaintenanceLogParams) (AssetMaintenanceLog, error) {
	row := q.db.QueryRow(ctx, updateMaintenanceLog, arg.ID, arg.Details, arg.Status)
	var i AssetMaintenanceLog
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.Details,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
