// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAssetMaster(ctx context.Context, name string) (AssetMaster, error)
	CreateMaintenanceLog(ctx context.Context, arg CreateMaintenanceLogParams) (AssetMaintenanceLog, error)
	DeleteAssetMaster(ctx context.Context, id uuid.UUID) error
	DeleteMaintenanceLog(ctx context.Context, id uuid.UUID) error
	GetMaintenanceLogsByAssetId(ctx context.Context, assetID uuid.UUID) ([]AssetMaintenanceLog, error)
	ListAssetMasters(ctx context.Context) ([]ListAssetMastersRow, error)
	ListAssets(ctx context.Context) ([]ListAssetsRow, error)
	ListAssetsByRoom(ctx context.Context, roomID uuid.UUID) ([]ListAssetsByRoomRow, error)
	UpdateAssetMaster(ctx context.Context, arg UpdateAssetMasterParams) (AssetMaster, error)
	UpdateMaintenanceLog(ctx context.Context, arg UpdateMaintenanceLogParams) (AssetMaintenanceLog, error)
}

var _ Querier = (*Queries)(nil)
