// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: finance.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFinancialRecord = `-- name: CreateFinancialRecord :one
INSERT INTO financial_records (type, amount, description, payment_id, date, asset_id, expense_category)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, type, amount, description, payment_id, created_at, updated_at, date, asset_id, expense_category
`

type CreateFinancialRecordParams struct {
	Type            TransactionTypeEnum     `json:"type"`
	Amount          pgtype.Numeric          `json:"amount"`
	Description     pgtype.Text             `json:"description"`
	PaymentID       pgtype.UUID             `json:"payment_id"`
	Date            pgtype.Timestamptz      `json:"date"`
	AssetID         pgtype.UUID             `json:"asset_id"`
	ExpenseCategory NullExpenseCategoryEnum `json:"expense_category"`
}

func (q *Queries) CreateFinancialRecord(ctx context.Context, arg CreateFinancialRecordParams) (FinancialRecord, error) {
	row := q.db.QueryRow(ctx, createFinancialRecord,
		arg.Type,
		arg.Amount,
		arg.Description,
		arg.PaymentID,
		arg.Date,
		arg.AssetID,
		arg.ExpenseCategory,
	)
	var i FinancialRecord
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Amount,
		&i.Description,
		&i.PaymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Date,
		&i.AssetID,
		&i.ExpenseCategory,
	)
	return i, err
}

const deleteFinancialRecord = `-- name: DeleteFinancialRecord :exec
DELETE FROM financial_records WHERE id = $1
`

func (q *Queries) DeleteFinancialRecord(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFinancialRecord, id)
	return err
}

const getAllFinancialRecords = `-- name: GetAllFinancialRecords :many
SELECT f.id, f.type, f.amount, f.description, f.payment_id, f.created_at, f.updated_at, f.date, f.asset_id, f.expense_category, p.import_code as payment_import_code, a.name as asset_name
FROM financial_records f
LEFT JOIN payments p ON f.payment_id = p.id
LEFT JOIN assets a ON f.asset_id = a.id
ORDER BY f.date DESC, f.created_at DESC
`

type GetAllFinancialRecordsRow struct {
	ID                uuid.UUID               `json:"id"`
	Type              TransactionTypeEnum     `json:"type"`
	Amount            pgtype.Numeric          `json:"amount"`
	Description       pgtype.Text             `json:"description"`
	PaymentID         pgtype.UUID             `json:"payment_id"`
	CreatedAt         pgtype.Timestamptz      `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz      `json:"updated_at"`
	Date              pgtype.Timestamptz      `json:"date"`
	AssetID           pgtype.UUID             `json:"asset_id"`
	ExpenseCategory   NullExpenseCategoryEnum `json:"expense_category"`
	PaymentImportCode pgtype.Text             `json:"payment_import_code"`
	AssetName         pgtype.Text             `json:"asset_name"`
}

func (q *Queries) GetAllFinancialRecords(ctx context.Context) ([]GetAllFinancialRecordsRow, error) {
	rows, err := q.db.Query(ctx, getAllFinancialRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllFinancialRecordsRow
	for rows.Next() {
		var i GetAllFinancialRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Amount,
			&i.Description,
			&i.PaymentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Date,
			&i.AssetID,
			&i.ExpenseCategory,
			&i.PaymentImportCode,
			&i.AssetName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE financial_records 
SET amount = $2, description = $3, expense_category = $4, date = $5, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND type = 'EXPENSE' RETURNING id, type, amount, description, payment_id, created_at, updated_at, date, asset_id, expense_category
`

type UpdateExpenseParams struct {
	ID              uuid.UUID               `json:"id"`
	Amount          pgtype.Numeric          `json:"amount"`
	Description     pgtype.Text             `json:"description"`
	ExpenseCategory NullExpenseCategoryEnum `json:"expense_category"`
	Date            pgtype.Timestamptz      `json:"date"`
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (FinancialRecord, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.ID,
		arg.Amount,
		arg.Description,
		arg.ExpenseCategory,
		arg.Date,
	)
	var i FinancialRecord
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Amount,
		&i.Description,
		&i.PaymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Date,
		&i.AssetID,
		&i.ExpenseCategory,
	)
	return i, err
}
