// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateFinancialRecord(ctx context.Context, arg CreateFinancialRecordParams) (FinancialRecord, error)
	DeleteFinancialRecord(ctx context.Context, id uuid.UUID) error
	GetAllFinancialRecords(ctx context.Context) ([]GetAllFinancialRecordsRow, error)
	UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (FinancialRecord, error)
}

var _ Querier = (*Queries)(nil)
