// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveTenantsCount = `-- name: GetActiveTenantsCount :one
SELECT COUNT(DISTINCT user_id) FROM occupant_details WHERE status = 'ACTIVE'
`

func (q *Queries) GetActiveTenantsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getActiveTenantsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMonthlyIncome = `-- name: GetMonthlyIncome :one
SELECT COALESCE(SUM(amount), 0)::numeric FROM financial_records 
WHERE type = 'INCOME' AND date >= $1 AND date <= $2
`

type GetMonthlyIncomeParams struct {
	Date   pgtype.Timestamptz `json:"date"`
	Date_2 pgtype.Timestamptz `json:"date_2"`
}

func (q *Queries) GetMonthlyIncome(ctx context.Context, arg GetMonthlyIncomeParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getMonthlyIncome, arg.Date, arg.Date_2)
	var column_1 pgtype.Numeric
	err := row.Scan(&column_1)
	return column_1, err
}

const getOccupiedRoomsCount = `-- name: GetOccupiedRoomsCount :one
SELECT COUNT(*) FROM rooms WHERE status = 'OCCUPIED'
`

func (q *Queries) GetOccupiedRoomsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getOccupiedRoomsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRecentActivities = `-- name: GetRecentActivities :many
SELECT fr.id, fr.amount, fr.date, fr.type, 
       COALESCE(p.payment_method, 'CASH')::text as method,
       COALESCE(od.name, 'System') as tenant_name
FROM financial_records fr
LEFT JOIN payments p ON fr.id = p.id
LEFT JOIN occupant_details od ON p.occupant_id = od.user_id
WHERE fr.type = 'INCOME'
ORDER BY fr.date DESC LIMIT 5
`

type GetRecentActivitiesRow struct {
	ID         uuid.UUID           `json:"id"`
	Amount     pgtype.Numeric      `json:"amount"`
	Date       pgtype.Timestamptz  `json:"date"`
	Type       TransactionTypeEnum `json:"type"`
	Method     string              `json:"method"`
	TenantName string              `json:"tenant_name"`
}

func (q *Queries) GetRecentActivities(ctx context.Context) ([]GetRecentActivitiesRow, error) {
	rows, err := q.db.Query(ctx, getRecentActivities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentActivitiesRow
	for rows.Next() {
		var i GetRecentActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Date,
			&i.Type,
			&i.Method,
			&i.TenantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentComplaints = `-- name: GetRecentComplaints :many
SELECT c.id, c.category::text as category, c.status::text as status, c.created_at, od.name as tenant_name
FROM complaints c
LEFT JOIN occupant_details od ON c.reported_by_id = od.user_id
ORDER BY c.created_at DESC LIMIT 5
`

type GetRecentComplaintsRow struct {
	ID         uuid.UUID          `json:"id"`
	Category   string             `json:"category"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	TenantName pgtype.Text        `json:"tenant_name"`
}

func (q *Queries) GetRecentComplaints(ctx context.Context) ([]GetRecentComplaintsRow, error) {
	rows, err := q.db.Query(ctx, getRecentComplaints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentComplaintsRow
	for rows.Next() {
		var i GetRecentComplaintsRow
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Status,
			&i.CreatedAt,
			&i.TenantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalExpense = `-- name: GetTotalExpense :one
SELECT COALESCE(SUM(amount), 0)::numeric FROM financial_records WHERE type = 'EXPENSE'
`

func (q *Queries) GetTotalExpense(ctx context.Context) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTotalExpense)
	var column_1 pgtype.Numeric
	err := row.Scan(&column_1)
	return column_1, err
}

const getTotalIncome = `-- name: GetTotalIncome :one
SELECT COALESCE(SUM(amount), 0)::numeric FROM financial_records WHERE type = 'INCOME'
`

func (q *Queries) GetTotalIncome(ctx context.Context) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTotalIncome)
	var column_1 pgtype.Numeric
	err := row.Scan(&column_1)
	return column_1, err
}

const getTotalRooms = `-- name: GetTotalRooms :one
SELECT COUNT(*) FROM rooms
`

func (q *Queries) GetTotalRooms(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalRooms)
	var count int64
	err := row.Scan(&count)
	return count, err
}
