// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateOccupancySnapshot(ctx context.Context, arg CreateOccupancySnapshotParams) (RoomOccupancySnapshot, error)
	GetActiveTenantsCount(ctx context.Context) (int64, error)
	GetMonthlyIncome(ctx context.Context, arg GetMonthlyIncomeParams) (pgtype.Numeric, error)
	GetOccupancySnapshots(ctx context.Context) ([]RoomOccupancySnapshot, error)
	GetOccupiedRoomsCount(ctx context.Context) (int64, error)
	GetRecentActivities(ctx context.Context) ([]GetRecentActivitiesRow, error)
	GetRecentComplaints(ctx context.Context) ([]GetRecentComplaintsRow, error)
	GetTotalExpense(ctx context.Context) (pgtype.Numeric, error)
	GetTotalIncome(ctx context.Context) (pgtype.Numeric, error)
	GetTotalOutstanding(ctx context.Context) (pgtype.Numeric, error)
	GetTotalRooms(ctx context.Context) (int64, error)
}

var _ Querier = (*Queries)(nil)
