// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (room_id, occupant_id, price_applied, period_start, period_end, status, is_dp_reservation, waiting_for_room_vacant, prior_occupant_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, room_id, occupant_id, price_applied, paid_nominal, period_start, period_end, status, note, created_at, updated_at, import_code, is_dp_reservation, waiting_for_room_vacant, prior_occupant_id
`

type CreateInvoiceParams struct {
	RoomID               uuid.UUID          `json:"room_id"`
	OccupantID           pgtype.UUID        `json:"occupant_id"`
	PriceApplied         pgtype.Numeric     `json:"price_applied"`
	PeriodStart          pgtype.Timestamptz `json:"period_start"`
	PeriodEnd            pgtype.Timestamptz `json:"period_end"`
	Status               PaymentStatusEnum  `json:"status"`
	IsDpReservation      bool               `json:"is_dp_reservation"`
	WaitingForRoomVacant bool               `json:"waiting_for_room_vacant"`
	PriorOccupantID      pgtype.UUID        `json:"prior_occupant_id"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.RoomID,
		arg.OccupantID,
		arg.PriceApplied,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Status,
		arg.IsDpReservation,
		arg.WaitingForRoomVacant,
		arg.PriorOccupantID,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.OccupantID,
		&i.PriceApplied,
		&i.PaidNominal,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImportCode,
		&i.IsDpReservation,
		&i.WaitingForRoomVacant,
		&i.PriorOccupantID,
	)
	return i, err
}

const createInvoicePayment = `-- name: CreateInvoicePayment :exec
INSERT INTO invoice_payments (invoice_id, payment_id, amount_applied)
VALUES ($1, $2, $3)
`

type CreateInvoicePaymentParams struct {
	InvoiceID     uuid.UUID      `json:"invoice_id"`
	PaymentID     uuid.UUID      `json:"payment_id"`
	AmountApplied pgtype.Numeric `json:"amount_applied"`
}

func (q *Queries) CreateInvoicePayment(ctx context.Context, arg CreateInvoicePaymentParams) error {
	_, err := q.db.Exec(ctx, createInvoicePayment, arg.InvoiceID, arg.PaymentID, arg.AmountApplied)
	return err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (occupant_id, amount, payment_method, note, payment_date, import_code)
VALUES ($1, $2, $3, $4, CURRENT_TIMESTAMP, $5) RETURNING id, occupant_id, amount, note, created_at, updated_at, import_code, payment_date, payment_method
`

type CreatePaymentParams struct {
	OccupantID    uuid.UUID         `json:"occupant_id"`
	Amount        pgtype.Numeric    `json:"amount"`
	PaymentMethod PaymentMethodEnum `json:"payment_method"`
	Note          pgtype.Text       `json:"note"`
	ImportCode    pgtype.Text       `json:"import_code"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.OccupantID,
		arg.Amount,
		arg.PaymentMethod,
		arg.Note,
		arg.ImportCode,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OccupantID,
		&i.Amount,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImportCode,
		&i.PaymentDate,
		&i.PaymentMethod,
	)
	return i, err
}

const getInvoice = `-- name: GetInvoice :one
SELECT id, room_id, occupant_id, price_applied, paid_nominal, period_start, period_end, status, note, created_at, updated_at, import_code, is_dp_reservation, waiting_for_room_vacant, prior_occupant_id FROM invoices WHERE id = $1 LIMIT 1
`

func (q *Queries) GetInvoice(ctx context.Context, id uuid.UUID) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoice, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.OccupantID,
		&i.PriceApplied,
		&i.PaidNominal,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImportCode,
		&i.IsDpReservation,
		&i.WaitingForRoomVacant,
		&i.PriorOccupantID,
	)
	return i, err
}

const listFinancialRecords = `-- name: ListFinancialRecords :many
SELECT id, type, amount, description, payment_id, created_at, updated_at, date, asset_id, expense_category FROM financial_records ORDER BY created_at DESC
`

func (q *Queries) ListFinancialRecords(ctx context.Context) ([]FinancialRecord, error) {
	rows, err := q.db.Query(ctx, listFinancialRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FinancialRecord
	for rows.Next() {
		var i FinancialRecord
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Amount,
			&i.Description,
			&i.PaymentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Date,
			&i.AssetID,
			&i.ExpenseCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFinancialRecordsWithDetails = `-- name: ListFinancialRecordsWithDetails :many
SELECT 
    fr.id, fr.type, fr.amount, fr.description, fr.payment_id, fr.created_at, fr.updated_at, fr.date, fr.asset_id, fr.expense_category,
    (SELECT json_build_object('id', u.id, 'email', u.email, 'occupantDetails', json_build_object('name', od.name, 'status', od.status)) 
     FROM users u JOIN occupant_details od ON u.id = od.user_id 
     JOIN payments p ON fr.payment_id = p.id WHERE p.occupant_id = u.id) as occupant,
    COALESCE(
        (SELECT json_agg(json_build_object(
            'id', ip.id,
            'amountApplied', ip.amount_applied,
            'invoice', json_build_object(
                'id', i.id,
                'periodStart', i.period_start,
                'periodEnd', i.period_end,
                'room', (SELECT json_build_object('id', r.id, 'name', r.name) FROM rooms r WHERE r.id = i.room_id)
            )
        ))
        FROM payments p
        JOIN invoice_payments ip ON ip.payment_id = p.id
        JOIN invoices i ON ip.invoice_id = i.id
        WHERE p.id = fr.payment_id),
        '[]'::json
    ) as invoice_payments
FROM financial_records fr
ORDER BY fr.created_at DESC
`

type ListFinancialRecordsWithDetailsRow struct {
	ID              uuid.UUID               `json:"id"`
	Type            TransactionTypeEnum     `json:"type"`
	Amount          pgtype.Numeric          `json:"amount"`
	Description     pgtype.Text             `json:"description"`
	PaymentID       pgtype.UUID             `json:"payment_id"`
	CreatedAt       pgtype.Timestamptz      `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz      `json:"updated_at"`
	Date            pgtype.Timestamptz      `json:"date"`
	AssetID         pgtype.UUID             `json:"asset_id"`
	ExpenseCategory NullExpenseCategoryEnum `json:"expense_category"`
	Occupant        []byte                  `json:"occupant"`
	InvoicePayments interface{}             `json:"invoice_payments"`
}

func (q *Queries) ListFinancialRecordsWithDetails(ctx context.Context) ([]ListFinancialRecordsWithDetailsRow, error) {
	rows, err := q.db.Query(ctx, listFinancialRecordsWithDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFinancialRecordsWithDetailsRow
	for rows.Next() {
		var i ListFinancialRecordsWithDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Amount,
			&i.Description,
			&i.PaymentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Date,
			&i.AssetID,
			&i.ExpenseCategory,
			&i.Occupant,
			&i.InvoicePayments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoices = `-- name: ListInvoices :many
SELECT id, room_id, occupant_id, price_applied, paid_nominal, period_start, period_end, status, note, created_at, updated_at, import_code, is_dp_reservation, waiting_for_room_vacant, prior_occupant_id FROM invoices ORDER BY period_start DESC
`

func (q *Queries) ListInvoices(ctx context.Context) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.OccupantID,
			&i.PriceApplied,
			&i.PaidNominal,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Status,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImportCode,
			&i.IsDpReservation,
			&i.WaitingForRoomVacant,
			&i.PriorOccupantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesWithDetails = `-- name: ListInvoicesWithDetails :many
SELECT 
    i.id, i.room_id, i.occupant_id, i.price_applied, i.paid_nominal, i.period_start, i.period_end, i.status, i.note, i.created_at, i.updated_at, i.import_code, i.is_dp_reservation, i.waiting_for_room_vacant, i.prior_occupant_id,
    (SELECT json_build_object('id', r.id, 'name', r.name, 'price', r.price) FROM rooms r WHERE r.id = i.room_id) as room,
    (SELECT json_build_object('id', u.id, 'email', u.email, 'occupantDetails', json_build_object('name', od.name, 'status', od.status)) 
     FROM users u JOIN occupant_details od ON u.id = od.user_id WHERE u.id = i.occupant_id) as occupant,
    (SELECT json_build_object('id', u.id, 'email', u.email, 'occupantDetails', json_build_object('name', od.name, 'status', od.status)) 
     FROM users u JOIN occupant_details od ON u.id = od.user_id WHERE u.id = i.prior_occupant_id) as prior_occupant,
    COALESCE(
        (SELECT json_agg(json_build_object(
            'id', ip.id,
            'amountApplied', ip.amount_applied,
            'payment', json_build_object(
                'id', p.id,
                'amount', p.amount,
                'paymentDate', p.payment_date,
                'paymentMethod', p.payment_method,
                'note', p.note
            )
        ))
        FROM invoice_payments ip
        JOIN payments p ON ip.payment_id = p.id
        WHERE ip.invoice_id = i.id),
        '[]'::json
    ) as invoice_payments
FROM invoices i
ORDER BY i.period_start DESC
`

type ListInvoicesWithDetailsRow struct {
	ID                   uuid.UUID          `json:"id"`
	RoomID               uuid.UUID          `json:"room_id"`
	OccupantID           pgtype.UUID        `json:"occupant_id"`
	PriceApplied         pgtype.Numeric     `json:"price_applied"`
	PaidNominal          pgtype.Numeric     `json:"paid_nominal"`
	PeriodStart          pgtype.Timestamptz `json:"period_start"`
	PeriodEnd            pgtype.Timestamptz `json:"period_end"`
	Status               PaymentStatusEnum  `json:"status"`
	Note                 pgtype.Text        `json:"note"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	ImportCode           pgtype.Text        `json:"import_code"`
	IsDpReservation      bool               `json:"is_dp_reservation"`
	WaitingForRoomVacant bool               `json:"waiting_for_room_vacant"`
	PriorOccupantID      pgtype.UUID        `json:"prior_occupant_id"`
	Room                 []byte             `json:"room"`
	Occupant             []byte             `json:"occupant"`
	PriorOccupant        []byte             `json:"prior_occupant"`
	InvoicePayments      interface{}        `json:"invoice_payments"`
}

func (q *Queries) ListInvoicesWithDetails(ctx context.Context) ([]ListInvoicesWithDetailsRow, error) {
	rows, err := q.db.Query(ctx, listInvoicesWithDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvoicesWithDetailsRow
	for rows.Next() {
		var i ListInvoicesWithDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.OccupantID,
			&i.PriceApplied,
			&i.PaidNominal,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Status,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImportCode,
			&i.IsDpReservation,
			&i.WaitingForRoomVacant,
			&i.PriorOccupantID,
			&i.Room,
			&i.Occupant,
			&i.PriorOccupant,
			&i.InvoicePayments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoiceStatus = `-- name: UpdateInvoiceStatus :exec
UPDATE invoices SET status = $2, paid_nominal = paid_nominal + $3 WHERE id = $1
`

type UpdateInvoiceStatusParams struct {
	ID          uuid.UUID         `json:"id"`
	Status      PaymentStatusEnum `json:"status"`
	PaidNominal pgtype.Numeric    `json:"paid_nominal"`
}

func (q *Queries) UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) error {
	_, err := q.db.Exec(ctx, updateInvoiceStatus, arg.ID, arg.Status, arg.PaidNominal)
	return err
}
